exports.values = [
  { id : "gyro",         label : "ジャイロセンサ値" },
  { id : "touch",        label : "タッチセンサ値" },
  { id : "sonar",        label : "ソナー値" },
  { id : "brightness",   label : "輝度値" },
  { id : "rgb_r",        label : "RGB(R値)" },
  { id : "rgb_g",        label : "RGB(G値)" },
  { id : "rgb_b",        label : "RGB(B値)" },
  { id : "hsv_h",        label : "HSV(H値)" },
  { id : "hsv_s",        label : "HSV(S値)" },
  { id : "hsv_v",        label : "HSV(V値)" },
  { id : "arm_count",    label : "前輪エンコーダ値" },
  { id : "left_count",   label : "左輪エンコーダ値" },
  { id : "right_count",  label : "右輪エンコーダ値" },
  { id : "length",       label : "走行距離" },
  { id : "angle",        label : "車体角度" },
  { id : "coordinate_x", label : "自己位置X座標" },
  { id : "coordinate_y", label : "自己位置Y座標" },
  { id : "clock",        label : "時刻" },
  { id : "battery_ma",   label : "バッテリ電流[mA]"},
  { id : "battery_mv",   label : "バッテリ電圧[mV]"}
];
